server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/KTX_Managerment"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    cors:
      allowed-origins:
        - http://localhost:5173
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
      max-age: 3600
logging:
  level:
    root: INFO
    cena.dorm_management: DEBUG

jwt:
  signerKey: "zY9BNzjkh3vxK/QgxppMK8Oixnod4/6LiSP+uFEbLVkNFgeRfGTHmQ8p0B1RgYqi"